name: C/C++ CI

on:
  push:
    branches: [ main, custom-streams ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-gcc10
      run:   |
         sudo apt update
         sudo apt install gcc-10 g++-10
    #- name: configure
      #run: ./configure
      #run: cmake .
    - run: cmake .
      env :
        CC:   gcc-10
        CXX:  g++-10
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
